name: ads_demo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  google_mobile_ads:
  get:
  flutter_screenutil: ^5.9.3
  intl_phone_number_input: ^0.7.3+1
  truecaller_sdk: ^1.2.0
  uuid: ^4.5.1
  permission_handler: ^11.3.1
  flutter_svg: ^2.0.10+1
  http: ^1.2.2
  shared_preferences: ^2.3.2
  logger: ^2.4.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
